#!/usr/bin/env ruby
# encoding: UTF-8
#
# tsvn_client_side_hook start-commit
#  - create version info file
#

VERSION_FILE    = 'src/main/Version.java'
SVN_VERSION     = `svnversion --no-newline`

def next_version()
    SVN_VERSION.to_i + 1
end

def create_version_file()
    open(VERSION_FILE, 'wb') { |f|
        f.puts "// This java source file is auto-genarated by '#{File.basename(__FILE__)}'"
        f.puts "// Do not edit this file"
        f.puts ""
        f.puts "package main;"
        f.puts ""
        f.puts "public final class Version {"
        f.puts "    public static final String REVISION    = \"#{next_version()}\";"
        f.puts "    public static final String COMMIT_TIME = \"#{Time.now}\";"
        f.puts "}"
    }
end

create_version_file()
