#!/usr/bin/env ruby
# encoding: UTF-8
#
# - initialize server tool
# 1) create _jar_list.txt for jar file check
#
# Usage:
#  > ruby init_tool.rb
#

require 'find'

# ----------------------------------------------------------------
# initialize

THIS_FILE_DIR  = File.dirname(File.expand_path(__FILE__))
CURRENT_DIR    = Dir.pwd

# ----------------------------------------------------------------
# utils

def get_files(dir, type)
    files = []

    Find.find(dir) { |file|
        files << file if file =~ /\.#{type}$/i
    }

    files
end

# ----------------------------------------------------------------
# methods

def create_jar_list_file()
    jar_list_file = 'lib/_jar_list.txt'
    jar_files     = get_files('lib', 'jar')

    File.open(jar_list_file, 'w') { |f|
        f.puts "# This jar list file is auto-genarated by '#{File.basename(__FILE__)}' at '#{Time.now}'"
        f.puts '# The following jars were used to create this tool'
        f.puts '# Release this file to final servers for this tool to check jars'
        f.puts '# Do not edit this file'
        f.puts

        jar_files.each { |jar|
            f.puts File.basename(jar)
        }
    }
end

# ----------------------------------------------------------------
# main entry

def main(argv)
    Dir.chdir THIS_FILE_DIR + '/..'
    create_jar_list_file()
    Dir.chdir CURRENT_DIR
end

main(ARGV)
